version: '3'
services:

  python_container_1:
    build: .
    container_name: python_container_1
    hostname: python_container_1
    ports:
     - "8080:8080"
    volumes:
      - ./:/app
    env_file:
      - .env

  python_container_2:
    build: .
    container_name: python_container_2
    hostname: python_container_2s
    ports:
     - "8080:8080"
    volumes:
      - ./:/app
    env_file:
      - .env
